apiVersion: apps/v1
kind: Deployment
metadata:
  name: yncrea-hellomicro
  labels:
    app.kubernetes.io/name: yncrea-hellomicro

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: yncrea-hellomicro
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yncrea-hellomicro
    spec:
      containers:
        - name: yncrea-hellomicro
          image: {{ .Values.image.repository }}:{{ .Values.image.version }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret.txt
                  name: yncrea-hellomicro-secret
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: yncrea-hellomicro-configmap
                  key: greeting
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP